package api

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"time"
)

// MaxBatchSize is the most measurements one POST /api/measurements/batch takes
// (backend/app/schemas/agent.py MAX_BATCH_SIZE).
const MaxBatchSize = 100

// Measurement is the body of POST /api/measurements
// (backend/app/schemas/agent.py MeasurementCreate). Values are raw: the
// status is set by the server (ADR-004); there is no school field (ADR-005).
type Measurement struct {
	// MeasurementUUID is generated by the agent at the moment of measurement: the idempotency key (ADR-006).
	MeasurementUUID string `json:"measurement_uuid"`
	// MeasuredAt is marshalled as RFC 3339 with the offset of the computer (ADR-014).
	MeasuredAt       time.Time `json:"measured_at"`
	ConnectionStatus string    `json:"connection_status"`
	DownloadMbps     *float64  `json:"download_mbps,omitempty"`
	UploadMbps       *float64  `json:"upload_mbps,omitempty"`
	PingMs           *float64  `json:"ping_ms,omitempty"`
	JitterMs         *float64  `json:"jitter_ms,omitempty"`
	PacketLossPct    *float64  `json:"packet_loss_pct,omitempty"`
	DurationS        *float64  `json:"duration_s,omitempty"`
	ExternalIP       string    `json:"external_ip,omitempty"`
	// Server is the measurement method and server address.
	Server       string `json:"server,omitempty"`
	IfaceType    string `json:"iface_type,omitempty"`
	AgentVersion string `json:"agent_version"`
}

// BatchResult is the answer for one item of a batch, in request order:
// 201 - stored, 409 - stored earlier. Both mean "delete from the queue".
type BatchResult struct {
	MeasurementUUID string `json:"measurement_uuid"`
	Status          int    `json:"status"`
	Type            string `json:"type,omitempty"`
}

// Delivered reports whether the server has the measurement.
func (r BatchResult) Delivered() bool {
	return r.Status == http.StatusCreated || r.Status == http.StatusConflict
}

// SendMeasurement sends one measurement. A duplicate (409) is not an error:
// the server already has it (ADR-006).
func (c *Client) SendMeasurement(ctx context.Context, m Measurement) error {
	err := c.do(ctx, http.MethodPost, "/measurements", m, nil)
	var pe *ProblemError
	if errors.As(err, &pe) && pe.Status == http.StatusConflict {
		return nil
	}
	return err
}

// SendMeasurementBatch sends up to MaxBatchSize measurements and returns the
// result for each. An invalid item rejects the whole batch with 422.
func (c *Client) SendMeasurementBatch(ctx context.Context, items []Measurement) ([]BatchResult, error) {
	if len(items) == 0 || len(items) > MaxBatchSize {
		return nil, fmt.Errorf("пакет замеров: %d записей, допустимо 1–%d", len(items), MaxBatchSize)
	}
	var resp struct {
		Results []BatchResult `json:"results"`
	}
	body := struct {
		Items []Measurement `json:"items"`
	}{items}
	if err := c.do(ctx, http.MethodPost, "/measurements/batch", body, &resp); err != nil {
		return nil, err
	}
	return resp.Results, nil
}

// Invalid reports whether the server rejected the request body as invalid
// (422): repeating the same data will never succeed.
func Invalid(err error) bool {
	var pe *ProblemError
	return errors.As(err, &pe) && pe.Status == http.StatusUnprocessableEntity
}
